### PR TITLE
#178: Resigning assemblies with an snk

### PR DESCRIPTION
**Pull request by AlexanderPruss**
@Master: This uses a .snk instead of a .pfx file.

### CODE REVIEW

**Comment by flcdrg** [comment]
Will this produce the same public key as the old versions?

**Comment by AlexanderPruss** [comment]
Good point. No, this would change the public key.

**Comment by flcdrg** [comment]
So if someone knew the password for the pfx, then you could use `sn -p strongname.pfx System.IO.Abstractions.snk` to extract the snk file, and I think that would probably result in keeping the same public key.

@tathamoddie ?

**Comment by tathamoddie** [comment]
I have the password for the PFX.

It used to be installed on the old TeamCity box, so the build process would pick it up.

When we moved to AppVeyor, I didn't have a solution for it.

I can easily unlock the pfx, or publish the password, but that feels wrong. I don't know why.

I'm not terribly familiar with AppVeyor yet, but I do know that they have a way of storing encrypted values. Can somebody help with a PR / pointers on how to securely use the current PFX?

**Comment by flcdrg** [comment]
Yes, you can define encrypted things with AppVeyor. Maybe it would need to be set as an environment variable that the csproj could pick up - but you'd want to do that in a way that didn't end up including the password in the build logs!

**Comment by flcdrg** [comment]
So looking at http://codecoding.com/using-appveyor-to-build-a-vsto-project/, the way they do it is:

- add an encrypted environment variable
- in a pre-build script, grab this value and use it to install the pfx in the user store

eg. 
```
	$psw = ConvertTo-SecureString $env:certificatePass -AsPlainText -Force
	Import-PfxCertificate -FilePath .\{Path-to-your-pfx-in-your-github-project}\Certificate.pfx -CertStoreLocation cert:\CurrentUser\My -Password $psw
```

**Comment by jpreese** [comment]
This PR is quite old and I have not been able to get in touch with the original author. Going to close to explore different avenues with AppVeyor

**Pull request closed without merging**
