### PR TITLE
dotnet core support

### PR DESCRIPTION
**Pull request by gavynriebau**
Ref: #148 

Changes to allow the solution to build for both .NET 40 and dotnet core rc1.
This includes:
- Updated solution to VS2015 format
- Changed projects to xproj format
- Added `#if` preprocessor statements to disable SerializableAttribute for dotnet core
- Added `#if` preprocessor statements to support differences in implementation between .NET 40 and .NET core.
- Updated Publish-Release.ps1 to use `dnu pack` to generate packages

### CODE REVIEW

**Comment by gavynriebau** [comment]
@tathamoddie Are you able to provide me with the logs from the teamcity build so I can figure out what I've broken?

**Comment by manne** [comment]
you can retrieve it [here](http://teamcity.tath.am/viewLog.html?buildId=3435&buildTypeId=bt21&tab=buildLog)

**Comment by gavynriebau** [comment]
@manne: Thanks,

I think this is just happening because the DNX tools aren't yet installed on the build server (similar to the problem [reported here](http://stackoverflow.com/questions/32762188/microsoft-dnx-props-not-found))

Installing VS 2015 on the teamcity build agent should fix it.

**Comment by laedit** [comment]
Is this project abandoned?
If the TeamCity is blocking and inaccessible, can I suggest to switch to [AppVeyor](https://appveyor.com)?

**Comment by tathamoddie** [comment]
Yep, TeamCity be dead, and my work focus has shifted quite significantly since starting this project. I'd totally support somebody else getting the build going again, and looking to take some ownership.

**Comment by laedit** [comment]
I will be happy to help as much as I can, but I don't have the required time to take the ownership on this project.

**Comment by tathamoddie** [comment]
AppVeyor is now in place. How do I poke it to re-run on existing PRs?

**Comment by laedit** [comment]
I think the only way is to `push` something in the branch.
Since .net core is officially out, you can take the opportunity to fix the version numbers.

**Comment by jpreese** [comment]
Closing this PR as we now support core.

**Pull request closed without merging**
