### PR TITLE
Remove all refs to System.Security.AccessControl from netstandard1.4 version

### PR DESCRIPTION
**Pull request by verybadcat**
With these changes, this will install in a Xamarin project.

That said, I am not an expert in this area whatsoever. It is possible that I removed the refs from too many environments.

### CODE REVIEW

**Comment by pasn** [comment]
TestingHelpers don't work for me without this fix because of #252 . This looks like possible fix for aforementioned issue. Could someone take a look on it?

**Comment by pasn** [comment]
Related: #272

**Comment by pasn** [comment]
I can confirm that my tests using this library started to work after I applied this patch. I used xunit.runner.devices to run my xunit tests inside real Xamarin.Forms app on Android.

**Comment by jpreese** [comment]
I am going to close this PR in favor of #289. Please continue the discussion there as they're both trying to solve the same problem.

**Pull request closed without merging**
