### PR TITLE
feat: Adding 'SubDirectory' and 'File' extension methods to IDirectoryInfo

### PR DESCRIPTION
**Pull request by gigi81**
A couple of simple extensions methods for IDirectoryInfo that I personally find extremely useful and saves me a lot of boilerplate code. I thought to share.

### CODE REVIEW

**Comment by fgreinacher** [comment]
Thanks a lot for your contribution @gigi81!

I am not going to merge this because I want to keep this library super-focused, acting as a drop-in replacement for `System.IO` and nothing else. See also similar discussions at https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/396, https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/662, https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/394 or https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/604.

I'd be open though for hosting a project maintained by someone else within the `System-IO-Abstractions` organization to keep related packages together (similar to https://github.com/System-IO-Abstractions/System.IO.Abstractions.Analyzers). Ping me if you want to go that way!

**Comment by gigi81** [comment]
Hi @fgreinacher I understand the reasoning. I think I could push the code to a separate repo if you were to create it. I may maintain it as well if you need someone dedicated. let me know

**Comment by fgreinacher** [comment]
> Hi @fgreinacher I understand the reasoning. I think I could push the code to a separate repo if you were to create it. I may maintain it as well if you need someone dedicated. let me know

Thanks @gigi81! I just created https://github.com/System-IO-Abstractions/System.IO.Abstractions.Extensions and added you as maintainer. Ping me in case you need any support 👍

**Comment by gigi81** [comment]
Thanks @fgreinacher I will init the repo and everything and let you know once I have it setup. Just give me a few days

**Pull request closed without merging**
