### PR TITLE
Fix #209: Add AllNodes

### LINKED ISSUE #209: Add AllLeaves to MockFileSystem
My testing would be simplified if I had access to an array of only the "leaves" of the file system (all the files, as well as empty folders).

For example, if `AllPaths` contain

````
C:\
C:\foo\
C:\bar\
C:\bar\baz\
C:\bar\baz\test1.txt
C:\bar\baz\test2.txt
````

then I would expect `AllLeaves` to contain

````
C:\foo\
C:\bar\baz\test1.txt
C:\bar\baz\test2.txt
````

Here's a quick and dirty implementation I made for testing, using LINQ:

````c#
private string[] AllLeaves(MockFileSystem fs)
{
    Func<string, bool> isNotStartOfAnotherPath =
        path => !fs.AllPaths.Any(otherPath => otherPath.StartsWith(path) && otherPath != path);

    return fs.AllPaths.Where(isNotStartOfAnotherPath).ToArray();
}
````

### PR DESCRIPTION
**Pull request by cmeeren**
Add AllNodes property with tests, as well as tests for AllPaths, AllNodes, AllFiles, and AllDirectories.

### CODE REVIEW

**Comment by jpreese** [comment]
Note, this is for #209

**Comment by jpreese** [comment]
I'm not really opposed to this feature, it's just a helper. Also adds cases for methods we already have that somehow escaped test coverage.

**Comment by fgreinacher** [comment]
@cmeeren Could you resolve the merge conflict?

**Comment by cmeeren** [comment]
This has been lying dormant for so long that I've long since moved on to other projects. I can't remember making this PR in the first place... :P Could anyone else take over this PR?

**Comment by jpreese** [comment]
Yeah, I'll take it over. Thanks for the ground work @cmeeren

**Comment by cmeeren** [comment]
Great, thanks!

**Comment by jpreese** [comment]
Closing for #323

**Pull request closed without merging**
