### PR TITLE
Add methods with EnumerationOptions parameter to IDirectoryInfo

### PR DESCRIPTION
**Pull request by sherman89**
In .NET Standard 2.1, new method overloads were introduced to DirectoryInfo that take in an EnumerationOptions as a parameter. This PR adds those.

### CODE REVIEW

**Comment by fgreinacher** [comment]
@sherman89 There are some compile errors at the moment. Do you need resolving them?

**Comment by P-Storm** [comment]
It looks like the abstract functions are not implemented in `MockDirectoryInfo`.

```c#
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.GetDirectories(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.EnumerateFiles(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.EnumerateFileSystemInfos(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.GetFileSystemInfos(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.EnumerateDirectories(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
         MockDirectoryInfo.cs(10,18): error CS0534: 'MockDirectoryInfo' does not implement inherited abstract member 'DirectoryInfoBase.GetFiles(string, EnumerationOptions)' [D:\a\System.IO.Abstractions\System.IO.Abstractions\src\System.IO.Abstractions.TestingHelpers\System.IO.Abstractions.TestingHelpers.csproj]
```

**Comment by sherman89** [comment]
@fgreinacher @P-Storm Oops sorry about that! Fixed it now :)

CI errors seemed not my fault and didn't notice build status anywhere. Hope the PR is ok now...

**Comment by fgreinacher** [comment]
> Oops sorry about that! Fixed it now :)

No worries, thank you!

> CI errors seemed not my fault and didn't notice build status anywhere. Hope the PR is ok now...

Seems like .NET Install action has introduced some breaking changes with https://github.com/actions/setup-dotnet/releases/tag/v1.7.0. I'll take care of this!

**Comment by fgreinacher** [comment]
https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/646 Fixes the CI issues.

**Comment by fgreinacher** [comment]
I bump the minor part of the version with https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/641/commits/6ac5b6734555bc384c82f7d8d2af503202859aa4 to reflect this new feature.

**Comment by fgreinacher** [comment]
Thanks a lot!

**Pull request merged**
