### PR TITLE
#187: Directory move shoud be able to move files, not just directories

### PR DESCRIPTION
**Pull request by AlexanderPruss**

### CODE REVIEW

**Comment by jpreese** [comment]
Just as a note, I did some conflict resolution locally, and this PR breaks some tests. May need to revisit.

**Comment by jpreese** [comment]
This is for #187

**Comment by fgreinacher** [comment]
@AlexanderPruss can you resolve the conflicts so that we see what tests are failing?

**Comment by jpreese** [comment]
@fgreinacher this is probably going to be another case of someone needing to take the PR over. I don't believe the original author is active anymore.

**Comment by AlexanderPruss** [comment]
I can try and take a look at this again, but it's been a while and I ended up setting the branch a bit confusingly :X

**Comment by ericnewton76** [comment]
Um, does this make sense?  Can you actually use System.IO.Directory.Move on a file and it works?

**Comment by jpreese** [comment]
Id have to run a test for it, but that would be my assumption as a directory it's considered to be a file.

**Comment by Kirides** [comment]
`File.Move(@"E:\TestDir", @"E:\TestDir2");` throws a `FileNotFoundException` saying "File "E:\TestDir" not found."

Directory.Move accepts Files though and moves them accordingly

**Comment by Kirides** [comment]
`File.Move(@"E:\TestDir", @"E:\TestDir2");` throws a `FileNotFoundException` saying "File "E:\TestDir" not found."

Directory.Move accepts Files though and moves them accordingly

**Comment by fgreinacher** [comment]
@AlexanderPruss Can you rebase this on current master?

**Comment by fgreinacher** [comment]
Closing in favor of #438

**Pull request closed without merging**
