### PR TITLE
feat: increase MockFileSystem constructor speed

### PR DESCRIPTION
**Pull request by jflepp**
The `MockFileSystem` constructor builds the internal `IDictionary<string, MockFileData>` from a given one. While doing so, its performance decreased significantly with large data sets.

This PR splits the internal dictionary into one containing the files and one containing the directories. Some of our internal test durations were decreased by a factor >10 with these changes.

We would be happy if we could get this speedup out of the box.

### CODE REVIEW

**Comment by fgreinacher** [comment]
Thanks a lot for your contribution! Can you share your test cases with numbers before and after this change? I have some concerns that this improves your specific use cases, but degrades performance for hot paths, mostly due to the double lookups.

**Comment by jflepp** [comment]
About the numbers: We implemented our use-case in the test `MockFileSystem_Constructor_InitializedQuicklyWithLargeAmountOfData`. On our system, the test takes about 14 minutes without the changes, with the changes about 4 seconds.

The double lookups do not affect how the code scales, it's just a constant that got a bit larger, whereas the adjustments we made changed the time complexity of the algorithm from super- to sub-linear.

**Comment by fgreinacher** [comment]
> About the numbers: We implemented our use-case in the test `MockFileSystem_Constructor_InitializedQuicklyWithLargeAmountOfData`. On our system, the test takes about 14 minutes without the changes, with the changes about 4 seconds.
> 
> The double lookups do not affect how the code scales, it's just a constant that got a bit larger, whereas the adjustments we made changed the time complexity of the algorithm from super- to sub-linear.

Oh sorry, I somehow missed the new test case. Thanks a lot, I'll have a deeper look next week 🤝

**Comment by schibu007** [comment]
After discussion with @jflepp, I created PR #698 as an alternative approach. @fgreinacher Please let us know, in which direction you prefer to go.

**Comment by fgreinacher** [comment]
Closing in favor of #698

**Pull request closed without merging**
